# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
      - image: localstack/localstack:latest
        name: localstack_main
        environment:
          DEBUG: 1
          SERVICES: s3,iam,lambda
    #        name: localstack_main
    #        environment:
    #          DEBUG: 1
    #          SERVICES: s3,iam,lambda
    environment:
      AWS_DEFAULT_REGION: us-west-2
      AWS_SECRET_ACCESS_KEY: test
      AWS_ACCESS_KEY_ID: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: env
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
#      - setup_remote_docker:
#          version: 20.10.6
      #      - run: sleep 40
      #      - run:
      #          name: Waiting for localstack to be ready
      #          command: dockerize -wait tcp://localhost:4566 -timeout 2m
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            GOFLAGS="-mod=mod" go test -timeout 180000ms -v -cover ./... \
            -coverprofile=/tmp/test-reports/cp.out
            echo "==> Ensure go-junit-report exists"
            which go-junit-report >/dev/null 2>&1 || \
            (cd /tmp; GO111MODULE=on go get -u github.com/jstemmer/go-junit-report@v0.9.1)
            GOFLAGS="-mod=mod" go test -timeout 1800000ms -v -cover ./... 2>&1 | go-junit-report > /tmp/test-reports/junit-report.xml
      - store_test_results:
          path: /tmp/test-reports